### ISSUE TITLE
Fallback command injected as text instead of being executed.

### ISSUE THREAD

**Issue by nicholasc** [Shougo/neocomplete.vim#425]
# Problems summary
While typing in Insert mode, neocomplete injects *\<Plug>(neocomplete_fallback)* as text.

It's been happening to me since 147c50e introduced the function `s:check_fallback.`
It ends up executing `s:complete_key("\<Plug>(neocomplete_fallback)")` which in terms executes `call feedkeys(a:key)` where `a:key` is equal to `\<Plug>(neocomplete_fallback)`. 

## Expected
Neocomplete menu should be displayed instead of the fallback command text being injected inside the buffer.

## Environment Information
 * OS: Max OS X Yosemite
 * Vim version: 7.4

## Minimal vimrc less than 50 lines

```
" Neocomplete configuration
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#min_keyword_length = 3
```
## Reproducable ways from Vim starting

 1. Open a file buffer.
 2. Type text in order to trigger neocomplete menu.
 3. Find out that text is being injected instead of menu opening command being executed.

## Screen shot
![screen shot 2015-06-29 at 2 31 12 pm](https://cloud.githubusercontent.com/assets/2378304/8415318/f2516004-1e6b-11e5-839f-6207863437c4.png)

**Comment by octref** [comment]
Same problem here.

The thing is that, only some text entries trigger this behavior for me.

The culprit seems to be [here](https://github.com/Shougo/neocomplete.vim/blob/771274c2f04060fab1fc793f6e02cfe3bd3a6732/autoload/neocomplete/handler.vim#L247-L260).

And indeed, only when I type something that `if empty(neocomplete.complete_sources)` would return true, does this behavior trigger.

**Comment by zerowidth** [comment]
Same problem here.

**Comment by Shougo** [comment]
Fixed.
