### ISSUE TITLE
Neocomplete and Tern.js

### ISSUE THREAD

**Issue by amadeus** [Shougo/neocomplete.vim#91]
So according to this [blog post](http://tilvim.com/2013/08/21/js-autocomplete.html), just by installing the [Tern.js](https://github.com/marijnh/tern_for_vim) vim plugin, YouCompleteMe gets automatic access to the Omnicomplete updates for JS.

Does this also apply to Neocomplete? Is there another necessary step? Or is just not possible?

**Comment by ldong** [comment]
Thank you, @rafi 

It works like a charm, after added this to my vimrc file,
`autocmd FileType javascript setlocal omnifunc=tern#Complete`

**Comment by mikeys** [comment]
@ldong @rafi @amadeus I know it's been a while since this last post.
Did you need to actually add this: `let g:neocomplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*`
to trigger the omnicomplete automatically? since adding `autocmd FileType javascript setlocal omnifunc=tern#Complete` alone didn't do the trick..

**Comment by ldong** [comment]
@mikeys 
No, see [it](https://gist.github.com/ldong/a4d4ba6f7e25fb87a114) yourself

**Comment by anoopd** [comment]
@ldong Were you able to get the keyboard shortcuts working properly ? Like
<leader> td  :TernDoc
<leader> tR :TernRename

etc :- ??  I can get the other things working but unable to get the keyboard shortcuts working.
